version: '2.2'
services:
  # es:
  #   image: docker.elastic.co/elasticsearch/elasticsearch:7.2.1
  #   ports:
  #   - 9200:9200
  #   - 9300:9300
  #   environment:
  #   - discovery.type=single-node
  redis:
    image: redis:latest
    ports:
      - 6379:6379
  database:
    image: postgres
    restart: always
    ports:
    - "5432"
    environment:
    - POSTGRES_DB=whatnot
    - POSTGRES_USER=admin
    - POSTGRES_PASSWORD=password123
    volumes:
    - db-data:/var/lib/postgresql/data
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=postgresql://admin:password123@database:5432/whatnot
      - REDIS_PORT=6379
      - REDIS_HOST=redis
      - VIRTUAL_HOST=whatnot.local
    hostname: backend
    volumes:
      -  .:/app
    ports:
      - "8000:8000"
    links:
      - database
      # - es
    depends_on:
      - database
      # - es

  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

volumes:
  db-data:
    driver: local
